### ISSUE TITLE
Request for Manual Sentence Segmentation Information in Shared Dataset

### ISSUE THREAD

**Issue by Xingxl2studious** [marzenakrp/LiteraryTranslation#1]
Dear Marzenakrp,

I hope this message finds you well. I recently came across your shared dataset on GitHub titled "[Dataset Name]" (link to the dataset). I must express my appreciation for your efforts in creating and sharing this valuable resource.

Upon examining the dataset, I noticed that the sentences in the source passage are not segmented. As I am currently working on a project that requires pre-segmented sentences, I would like to kindly request your assistance in obtaining information regarding the manual sentence segmentation of the text in this dataset. Specifically, it would be helpful if you could provide the results after each paragraph has been manually split. By incorporating this additional feature, your dataset could cater to a wider audience and serve as a valuable resource for researchers and practitioners in various natural language processing tasks.

Thank you for considering my request. I eagerly await your response and look forward to any assistance you can provide. Please feel free to reach out to me if you have any questions or require further clarification.

Best regards

**Comment by marzenakrp** [comment]
I've added sentencized source data. Sadly, we do not have sentence level alignments between the source text and model generated translations (unless you need the sent setup translations which were done on the sentence level).
