### ISSUE TITLE
Mistranslation subcategory annotations

### ISSUE THREAD

**Issue by florinavogel** [marzenakrp/LiteraryTranslation#2]
Dear @marzenakrp 

In the paper in Section 6.2 you mention that you manually classify all annotated mistranslations into subcategories. As far as I can see, these subcategory annotations are not present in the annotations files. Do you by any chance have this data available and would you be able to share it? 

Thank you very much!

**Comment by marzenakrp** [comment]
Hi @florinavogel 

Sadly, this was done by going through translations and adding the count to spreadsheet, so we don't have that annotated (I only have the counts). Was this great? Not really, but there were other technical/time-related issues that led to this. I'm afraid that I don't have the capability to go back and make this available for each span.

**Comment by florinavogel** [comment]
I understand, thank you very much for your quick reply!
